#cloud-config
users:
  - name: user
    groups: sudo
    shell: /bin/bash
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    ssh_authorized_keys:
      - ssh-ed25519 27FQOvNSCs48aPXTvHfM9VUNcxzSCYh7uwmdExaAvm8 commertech@commertech-ubuntu